[package]
name = "rjdebounce"
version = "0.1.0"
authors = ["Jack <jackmead515@gmail.com>"]
edition = "2018"
description = "Debouncing function utility"
keywords = [ "debounce", "utility", "function" ]
categories = [ "rust-patterns" ]
license = "WTFPL"
license-file = "LICENSE.txt"

[dependencies]
